spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: boseok
    password: iotiot
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: bs

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org:
      springframework: DEBUG

# swagger 사용여부(true)
springdoc:
  swagger-ui:
    enabled: true
